export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISH = 'FINISH_QUIZ';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

export const QUIZ_QUESTION_CREATE = 'QUIZ_QUESTION_CREATE';
export const QUIZ_CREATION_RESET = 'QUIZ_CREATION_RESET';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';